- name: Installing Helm
  shell: |
    curl -fsSL -o /tmp/get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4
    chmod 700 /tmp/get_helm.sh
    /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm
