ansible_connection: aws_ssm
ansible_aws_ssm_bucket_name: nsse-ansible-ssm-495624154773
terraform_path: /home/paulo/Repositories/nsse-iac/terraform
kube_config: /etc/kubernetes/admin.conf
kube_config_worker: /etc/kubernetes/kubelet.conf
aws_profile: default
aws_region: us-east-1