- name: Setting Up Cluster
  hosts: aws_ec2
  become: true
  gather_facts: false
  pre_tasks:
    - name: Wait For SSM Connectivity
      wait_for_connection:
        delay: 15
        timeout: 600
    - name: Gather Facts
      setup:
  roles:
    - hostnames
    - dependency-packages
    - kube-packages
    - container-runtime

- name: Init Cluster
  hosts: control_planes[0]
  become: true
  environment:
    KUBECONFIG: "{{ kube_config }}"
  roles:
    - init-cluster
    - cloud-controller-manager
    - set-provider-id
    - container-network

- name: Join Control Planes
  hosts: control_planes:!control_planes[0]
  become: true
  environment:
    KUBECONFIG: "{{ kube_config }}"
  roles:
    - kubelet-extra-args
    - join-control-planes
    - set-provider-id

- name: Join Workers
  hosts: workers
  become: true
  environment:
    KUBECONFIG: "{{ kube_config_worker }}"
  roles:
    - kubelet-extra-args
    - join-workers
    - set-provider-id

- name: Update Launch Template
  hosts: localhost
  gather_facts: false
  roles:
    - update-launch-template

- name: Setting Up Cluster Auto Scaler
  hosts: control_planes[0]
  become: true
  environment:
    KUBECONFIG: "{{ kube_config }}"
  roles:
    - helm
    - node-termination
    - cluster-autoscaler
    - argo-rollouts
    - argocd
    - metrics-server
    - load-balancer-controller
    - container-storage
    - external-dns
    - fluent-bit

    


  