- name: Generate Join Command
  shell: kubeadm token create --print-join-command --ttl 0
  register: join_command_output

- name: Generate Certificate Key
  shell: kubeadm init phase upload-certs --upload-certs | tail -n 1
  register: certificate_key_output

- name: Write Control Plane Join Command To File
  copy:
    content: "{{ join_command_output.stdout }} --control-plane --certificate-key {{certificate_key_output.stdout}}"
    dest: /tmp/kubeadm-join-control-plane.txt
  delegate_to: localhost
  become: false
  run_once: true

- name: Write Worker Join Command To File
  copy:
    content: "{{ join_command_output.stdout }}"
    dest: /tmp/kubeadm-join-worker.txt
  delegate_to: localhost
  become: false
  run_once: true