- name: Copy Template File
  vars:
    terraform_outputs: "{{ lookup('file', terraform_path ~ '/server/outputs.json') | from_json }}"
    nlb_dns_name: "{{ terraform_outputs.nlb_dns_name.value }}"
  template:
    src: kubeadm-init.yml
    dest: /home/admin/kubeadm-init.yml